import Link from "next/link";
import Image from "next/image";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

const childWidthStyles = "w-full mx-auto px-6 max-w-5xl";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="w-full flex items-center py-5 justify-center border-b">
          <nav
            className={`${childWidthStyles} flex gap-10 justify-end items-center font-semibold`}
          >
            <Link href="/blog" className="mr-auto">
              <Image
                width={50}
                height={50}
                src="/placeholder logo.png"
                alt="Kevins logo"
              />
            </Link>
            <Link href="/blog">Blog</Link>
            <Link href="/craft">Craft</Link>
            <Link href="/art">Art</Link>
          </nav>
        </header>
        <main className="w-full">
          <section className={`${childWidthStyles} w-full py-6`}>
            {children}
          </section>
        </main>
      </body>
    </html>
  );
}
